// Code generated by go-swagger; DO NOT EDIT.

package inverter_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLatestEnergyDataParams creates a new GetLatestEnergyDataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLatestEnergyDataParams() *GetLatestEnergyDataParams {
	return &GetLatestEnergyDataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLatestEnergyDataParamsWithTimeout creates a new GetLatestEnergyDataParams object
// with the ability to set a timeout on a request.
func NewGetLatestEnergyDataParamsWithTimeout(timeout time.Duration) *GetLatestEnergyDataParams {
	return &GetLatestEnergyDataParams{
		timeout: timeout,
	}
}

// NewGetLatestEnergyDataParamsWithContext creates a new GetLatestEnergyDataParams object
// with the ability to set a context for a request.
func NewGetLatestEnergyDataParamsWithContext(ctx context.Context) *GetLatestEnergyDataParams {
	return &GetLatestEnergyDataParams{
		Context: ctx,
	}
}

// NewGetLatestEnergyDataParamsWithHTTPClient creates a new GetLatestEnergyDataParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLatestEnergyDataParamsWithHTTPClient(client *http.Client) *GetLatestEnergyDataParams {
	return &GetLatestEnergyDataParams{
		HTTPClient: client,
	}
}

/*
GetLatestEnergyDataParams contains all the parameters to send to the API endpoint

	for the get latest energy data operation.

	Typically these are written to a http.Request.
*/
type GetLatestEnergyDataParams struct {

	// Authorization.
	Authorization *string

	/* InverterSerialNumber.

	   The serial number of the inverter.
	*/
	InverterSerialNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get latest energy data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLatestEnergyDataParams) WithDefaults() *GetLatestEnergyDataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get latest energy data params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLatestEnergyDataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get latest energy data params
func (o *GetLatestEnergyDataParams) WithTimeout(timeout time.Duration) *GetLatestEnergyDataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get latest energy data params
func (o *GetLatestEnergyDataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get latest energy data params
func (o *GetLatestEnergyDataParams) WithContext(ctx context.Context) *GetLatestEnergyDataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get latest energy data params
func (o *GetLatestEnergyDataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get latest energy data params
func (o *GetLatestEnergyDataParams) WithHTTPClient(client *http.Client) *GetLatestEnergyDataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get latest energy data params
func (o *GetLatestEnergyDataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get latest energy data params
func (o *GetLatestEnergyDataParams) WithAuthorization(authorization *string) *GetLatestEnergyDataParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get latest energy data params
func (o *GetLatestEnergyDataParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithInverterSerialNumber adds the inverterSerialNumber to the get latest energy data params
func (o *GetLatestEnergyDataParams) WithInverterSerialNumber(inverterSerialNumber string) *GetLatestEnergyDataParams {
	o.SetInverterSerialNumber(inverterSerialNumber)
	return o
}

// SetInverterSerialNumber adds the inverterSerialNumber to the get latest energy data params
func (o *GetLatestEnergyDataParams) SetInverterSerialNumber(inverterSerialNumber string) {
	o.InverterSerialNumber = inverterSerialNumber
}

// WriteToRequest writes these params to a swagger request
func (o *GetLatestEnergyDataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param inverter_serial_number
	if err := r.SetPathParam("inverter_serial_number", o.InverterSerialNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
