// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSendNotificationParams creates a new SendNotificationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendNotificationParams() *SendNotificationParams {
	return &SendNotificationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendNotificationParamsWithTimeout creates a new SendNotificationParams object
// with the ability to set a timeout on a request.
func NewSendNotificationParamsWithTimeout(timeout time.Duration) *SendNotificationParams {
	return &SendNotificationParams{
		timeout: timeout,
	}
}

// NewSendNotificationParamsWithContext creates a new SendNotificationParams object
// with the ability to set a context for a request.
func NewSendNotificationParamsWithContext(ctx context.Context) *SendNotificationParams {
	return &SendNotificationParams{
		Context: ctx,
	}
}

// NewSendNotificationParamsWithHTTPClient creates a new SendNotificationParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendNotificationParamsWithHTTPClient(client *http.Client) *SendNotificationParams {
	return &SendNotificationParams{
		HTTPClient: client,
	}
}

/*
SendNotificationParams contains all the parameters to send to the API endpoint

	for the send notification operation.

	Typically these are written to a http.Request.
*/
type SendNotificationParams struct {

	// Authorization.
	Authorization *string

	// Body.
	Body SendNotificationBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendNotificationParams) WithDefaults() *SendNotificationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send notification params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendNotificationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send notification params
func (o *SendNotificationParams) WithTimeout(timeout time.Duration) *SendNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send notification params
func (o *SendNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send notification params
func (o *SendNotificationParams) WithContext(ctx context.Context) *SendNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send notification params
func (o *SendNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send notification params
func (o *SendNotificationParams) WithHTTPClient(client *http.Client) *SendNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send notification params
func (o *SendNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the send notification params
func (o *SendNotificationParams) WithAuthorization(authorization *string) *SendNotificationParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the send notification params
func (o *SendNotificationParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the send notification params
func (o *SendNotificationParams) WithBody(body SendNotificationBody) *SendNotificationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send notification params
func (o *SendNotificationParams) SetBody(body SendNotificationBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SendNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
