// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountInformationByIDParams creates a new GetAccountInformationByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountInformationByIDParams() *GetAccountInformationByIDParams {
	return &GetAccountInformationByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountInformationByIDParamsWithTimeout creates a new GetAccountInformationByIDParams object
// with the ability to set a timeout on a request.
func NewGetAccountInformationByIDParamsWithTimeout(timeout time.Duration) *GetAccountInformationByIDParams {
	return &GetAccountInformationByIDParams{
		timeout: timeout,
	}
}

// NewGetAccountInformationByIDParamsWithContext creates a new GetAccountInformationByIDParams object
// with the ability to set a context for a request.
func NewGetAccountInformationByIDParamsWithContext(ctx context.Context) *GetAccountInformationByIDParams {
	return &GetAccountInformationByIDParams{
		Context: ctx,
	}
}

// NewGetAccountInformationByIDParamsWithHTTPClient creates a new GetAccountInformationByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountInformationByIDParamsWithHTTPClient(client *http.Client) *GetAccountInformationByIDParams {
	return &GetAccountInformationByIDParams{
		HTTPClient: client,
	}
}

/*
GetAccountInformationByIDParams contains all the parameters to send to the API endpoint

	for the get account information by ID operation.

	Typically these are written to a http.Request.
*/
type GetAccountInformationByIDParams struct {

	// Authorization.
	Authorization *string

	/* UserID.

	   The ID of the user.
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get account information by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountInformationByIDParams) WithDefaults() *GetAccountInformationByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get account information by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountInformationByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get account information by ID params
func (o *GetAccountInformationByIDParams) WithTimeout(timeout time.Duration) *GetAccountInformationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account information by ID params
func (o *GetAccountInformationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account information by ID params
func (o *GetAccountInformationByIDParams) WithContext(ctx context.Context) *GetAccountInformationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account information by ID params
func (o *GetAccountInformationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account information by ID params
func (o *GetAccountInformationByIDParams) WithHTTPClient(client *http.Client) *GetAccountInformationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account information by ID params
func (o *GetAccountInformationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get account information by ID params
func (o *GetAccountInformationByIDParams) WithAuthorization(authorization *string) *GetAccountInformationByIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get account information by ID params
func (o *GetAccountInformationByIDParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithUserID adds the userID to the get account information by ID params
func (o *GetAccountInformationByIDParams) WithUserID(userID string) *GetAccountInformationByIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get account information by ID params
func (o *GetAccountInformationByIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountInformationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
