// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAccountDonglesByIDParams creates a new GetAccountDonglesByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountDonglesByIDParams() *GetAccountDonglesByIDParams {
	return &GetAccountDonglesByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountDonglesByIDParamsWithTimeout creates a new GetAccountDonglesByIDParams object
// with the ability to set a timeout on a request.
func NewGetAccountDonglesByIDParamsWithTimeout(timeout time.Duration) *GetAccountDonglesByIDParams {
	return &GetAccountDonglesByIDParams{
		timeout: timeout,
	}
}

// NewGetAccountDonglesByIDParamsWithContext creates a new GetAccountDonglesByIDParams object
// with the ability to set a context for a request.
func NewGetAccountDonglesByIDParamsWithContext(ctx context.Context) *GetAccountDonglesByIDParams {
	return &GetAccountDonglesByIDParams{
		Context: ctx,
	}
}

// NewGetAccountDonglesByIDParamsWithHTTPClient creates a new GetAccountDonglesByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountDonglesByIDParamsWithHTTPClient(client *http.Client) *GetAccountDonglesByIDParams {
	return &GetAccountDonglesByIDParams{
		HTTPClient: client,
	}
}

/*
GetAccountDonglesByIDParams contains all the parameters to send to the API endpoint

	for the get account dongles by ID operation.

	Typically these are written to a http.Request.
*/
type GetAccountDonglesByIDParams struct {

	// Authorization.
	Authorization *string

	/* Page.

	   Page number to return
	*/
	Page *int64

	/* PageSize.

	   Number of items to return in a page. Defaults to 15
	*/
	PageSize *int64

	/* UserUsername.

	   The username of the user.
	*/
	UserUsername string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get account dongles by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountDonglesByIDParams) WithDefaults() *GetAccountDonglesByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get account dongles by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountDonglesByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithTimeout(timeout time.Duration) *GetAccountDonglesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithContext(ctx context.Context) *GetAccountDonglesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithHTTPClient(client *http.Client) *GetAccountDonglesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithAuthorization(authorization *string) *GetAccountDonglesByIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithPage adds the page to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithPage(page *int64) *GetAccountDonglesByIDParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithPageSize(pageSize *int64) *GetAccountDonglesByIDParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithUserUsername adds the userUsername to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) WithUserUsername(userUsername string) *GetAccountDonglesByIDParams {
	o.SetUserUsername(userUsername)
	return o
}

// SetUserUsername adds the userUsername to the get account dongles by ID params
func (o *GetAccountDonglesByIDParams) SetUserUsername(userUsername string) {
	o.UserUsername = userUsername
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountDonglesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	// path param user_username
	if err := r.SetPathParam("user_username", o.UserUsername); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
