// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetYourEVChargersReader is a Reader for the GetYourEVChargers structure.
type GetYourEVChargersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetYourEVChargersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetYourEVChargersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ev-charger] getYourEVChargers", response, response.Code())
	}
}

// NewGetYourEVChargersOK creates a GetYourEVChargersOK with default headers values
func NewGetYourEVChargersOK() *GetYourEVChargersOK {
	return &GetYourEVChargersOK{}
}

/*
GetYourEVChargersOK describes a response with status code 200, with default header values.

GetYourEVChargersOK get your e v chargers o k
*/
type GetYourEVChargersOK struct {
	Payload *GetYourEVChargersOKBody
}

// IsSuccess returns true when this get your e v chargers o k response has a 2xx status code
func (o *GetYourEVChargersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get your e v chargers o k response has a 3xx status code
func (o *GetYourEVChargersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get your e v chargers o k response has a 4xx status code
func (o *GetYourEVChargersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get your e v chargers o k response has a 5xx status code
func (o *GetYourEVChargersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get your e v chargers o k response a status code equal to that given
func (o *GetYourEVChargersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get your e v chargers o k response
func (o *GetYourEVChargersOK) Code() int {
	return 200
}

func (o *GetYourEVChargersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ev-charger][%d] getYourEVChargersOK %s", 200, payload)
}

func (o *GetYourEVChargersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ev-charger][%d] getYourEVChargersOK %s", 200, payload)
}

func (o *GetYourEVChargersOK) GetPayload() *GetYourEVChargersOKBody {
	return o.Payload
}

func (o *GetYourEVChargersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetYourEVChargersOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetYourEVChargersOKBody get your e v chargers o k body
// Example: {"data":[{"alias":"Garage","online":false,"serial_number":2622517580214,"status":"Charging","type":"GivEnergy","uuid":"b4100ebe-079d-4048-b998-48def0555967","went_offline_at":null},{"alias":"EV Charger 1","online":false,"serial_number":"23923227938057","status":"Finishing","type":"GivEnergy","uuid":"95c43bf5-03e6-415f-b667-16a188d42def","went_offline_at":null}]}
swagger:model GetYourEVChargersOKBody
*/
type GetYourEVChargersOKBody struct {

	// data
	// Example: [{"alias":"Garage","online":false,"serial_number":2622517580214,"status":"Charging","type":"GivEnergy","uuid":"b4100ebe-079d-4048-b998-48def0555967","went_offline_at":null},{"alias":"EV Charger 1","online":false,"serial_number":"23923227938057","status":"Finishing","type":"GivEnergy","uuid":"95c43bf5-03e6-415f-b667-16a188d42def","went_offline_at":null}]
	Data []*GetYourEVChargersOKBodyDataItems0 `json:"data"`
}

// Validate validates this get your e v chargers o k body
func (o *GetYourEVChargersOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetYourEVChargersOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getYourEVChargersOK" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getYourEVChargersOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get your e v chargers o k body based on the context it is used
func (o *GetYourEVChargersOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetYourEVChargersOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getYourEVChargersOK" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getYourEVChargersOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetYourEVChargersOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetYourEVChargersOKBody) UnmarshalBinary(b []byte) error {
	var res GetYourEVChargersOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetYourEVChargersOKBodyDataItems0 get your e v chargers o k body data items0
swagger:model GetYourEVChargersOKBodyDataItems0
*/
type GetYourEVChargersOKBodyDataItems0 struct {

	// alias
	// Example: Garage
	Alias string `json:"alias,omitempty"`

	// online
	// Example: false
	Online bool `json:"online,omitempty"`

	// serial number
	// Example: 2622517580214
	SerialNumber string `json:"serial_number,omitempty"`

	// status
	// Example: Charging
	Status string `json:"status,omitempty"`

	// type
	// Example: GivEnergy
	Type string `json:"type,omitempty"`

	// uuid
	// Example: b4100ebe-079d-4048-b998-48def0555967
	UUID string `json:"uuid,omitempty"`

	// went offline at
	WentOfflineAt string `json:"went_offline_at,omitempty"`
}

// Validate validates this get your e v chargers o k body data items0
func (o *GetYourEVChargersOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get your e v chargers o k body data items0 based on context it is used
func (o *GetYourEVChargersOKBodyDataItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetYourEVChargersOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetYourEVChargersOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetYourEVChargersOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
