// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSupportedCommandsReader is a Reader for the GetSupportedCommands structure.
type GetSupportedCommandsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSupportedCommandsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSupportedCommandsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSupportedCommandsOK creates a GetSupportedCommandsOK with default headers values
func NewGetSupportedCommandsOK() *GetSupportedCommandsOK {
	return &GetSupportedCommandsOK{}
}

/*
GetSupportedCommandsOK describes a response with status code 200, with default header values.

GetSupportedCommandsOK get supported commands o k
*/
type GetSupportedCommandsOK struct {
	Payload *GetSupportedCommandsOKBody
}

// IsSuccess returns true when this get supported commands o k response has a 2xx status code
func (o *GetSupportedCommandsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get supported commands o k response has a 3xx status code
func (o *GetSupportedCommandsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get supported commands o k response has a 4xx status code
func (o *GetSupportedCommandsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get supported commands o k response has a 5xx status code
func (o *GetSupportedCommandsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get supported commands o k response a status code equal to that given
func (o *GetSupportedCommandsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get supported commands o k response
func (o *GetSupportedCommandsOK) Code() int {
	return 200
}

func (o *GetSupportedCommandsOK) Error() string {
	return fmt.Sprintf("[GET /ev-charger/{charger_uuid}/commands][%d] getSupportedCommandsOK  %+v", 200, o.Payload)
}

func (o *GetSupportedCommandsOK) String() string {
	return fmt.Sprintf("[GET /ev-charger/{charger_uuid}/commands][%d] getSupportedCommandsOK  %+v", 200, o.Payload)
}

func (o *GetSupportedCommandsOK) GetPayload() *GetSupportedCommandsOKBody {
	return o.Payload
}

func (o *GetSupportedCommandsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSupportedCommandsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetSupportedCommandsOKBody get supported commands o k body
// Example: {"data":["start-charge","stop-charge","set-plug-and-go","set-session-energy-limit","set-schedule","change-mode"]}
swagger:model GetSupportedCommandsOKBody
*/
type GetSupportedCommandsOKBody struct {

	// data
	// Example: ["start-charge","stop-charge","set-plug-and-go","set-session-energy-limit","set-schedule","change-mode"]
	Data []string `json:"data"`
}

// Validate validates this get supported commands o k body
func (o *GetSupportedCommandsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get supported commands o k body based on context it is used
func (o *GetSupportedCommandsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSupportedCommandsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSupportedCommandsOKBody) UnmarshalBinary(b []byte) error {
	var res GetSupportedCommandsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
