// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetYourEVChargersParams creates a new GetYourEVChargersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetYourEVChargersParams() *GetYourEVChargersParams {
	return &GetYourEVChargersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetYourEVChargersParamsWithTimeout creates a new GetYourEVChargersParams object
// with the ability to set a timeout on a request.
func NewGetYourEVChargersParamsWithTimeout(timeout time.Duration) *GetYourEVChargersParams {
	return &GetYourEVChargersParams{
		timeout: timeout,
	}
}

// NewGetYourEVChargersParamsWithContext creates a new GetYourEVChargersParams object
// with the ability to set a context for a request.
func NewGetYourEVChargersParamsWithContext(ctx context.Context) *GetYourEVChargersParams {
	return &GetYourEVChargersParams{
		Context: ctx,
	}
}

// NewGetYourEVChargersParamsWithHTTPClient creates a new GetYourEVChargersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetYourEVChargersParamsWithHTTPClient(client *http.Client) *GetYourEVChargersParams {
	return &GetYourEVChargersParams{
		HTTPClient: client,
	}
}

/*
GetYourEVChargersParams contains all the parameters to send to the API endpoint

	for the get your e v chargers operation.

	Typically these are written to a http.Request.
*/
type GetYourEVChargersParams struct {

	// Authorization.
	Authorization *string

	/* Page.

	   Page number to return
	*/
	Page *int64

	/* PageSize.

	   Number of items to return in a page. Defaults to 15
	*/
	PageSize *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get your e v chargers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYourEVChargersParams) WithDefaults() *GetYourEVChargersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get your e v chargers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYourEVChargersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get your e v chargers params
func (o *GetYourEVChargersParams) WithTimeout(timeout time.Duration) *GetYourEVChargersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get your e v chargers params
func (o *GetYourEVChargersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get your e v chargers params
func (o *GetYourEVChargersParams) WithContext(ctx context.Context) *GetYourEVChargersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get your e v chargers params
func (o *GetYourEVChargersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get your e v chargers params
func (o *GetYourEVChargersParams) WithHTTPClient(client *http.Client) *GetYourEVChargersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get your e v chargers params
func (o *GetYourEVChargersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get your e v chargers params
func (o *GetYourEVChargersParams) WithAuthorization(authorization *string) *GetYourEVChargersParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get your e v chargers params
func (o *GetYourEVChargersParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithPage adds the page to the get your e v chargers params
func (o *GetYourEVChargersParams) WithPage(page *int64) *GetYourEVChargersParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get your e v chargers params
func (o *GetYourEVChargersParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get your e v chargers params
func (o *GetYourEVChargersParams) WithPageSize(pageSize *int64) *GetYourEVChargersParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get your e v chargers params
func (o *GetYourEVChargersParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *GetYourEVChargersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
