// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEVChargerByUUIDParams creates a new GetEVChargerByUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEVChargerByUUIDParams() *GetEVChargerByUUIDParams {
	return &GetEVChargerByUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEVChargerByUUIDParamsWithTimeout creates a new GetEVChargerByUUIDParams object
// with the ability to set a timeout on a request.
func NewGetEVChargerByUUIDParamsWithTimeout(timeout time.Duration) *GetEVChargerByUUIDParams {
	return &GetEVChargerByUUIDParams{
		timeout: timeout,
	}
}

// NewGetEVChargerByUUIDParamsWithContext creates a new GetEVChargerByUUIDParams object
// with the ability to set a context for a request.
func NewGetEVChargerByUUIDParamsWithContext(ctx context.Context) *GetEVChargerByUUIDParams {
	return &GetEVChargerByUUIDParams{
		Context: ctx,
	}
}

// NewGetEVChargerByUUIDParamsWithHTTPClient creates a new GetEVChargerByUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEVChargerByUUIDParamsWithHTTPClient(client *http.Client) *GetEVChargerByUUIDParams {
	return &GetEVChargerByUUIDParams{
		HTTPClient: client,
	}
}

/*
GetEVChargerByUUIDParams contains all the parameters to send to the API endpoint

	for the get e v charger by UUID operation.

	Typically these are written to a http.Request.
*/
type GetEVChargerByUUIDParams struct {

	// Authorization.
	Authorization *string

	/* ChargerUUID.

	   The UUID of the charger.
	*/
	ChargerUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get e v charger by UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEVChargerByUUIDParams) WithDefaults() *GetEVChargerByUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get e v charger by UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEVChargerByUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) WithTimeout(timeout time.Duration) *GetEVChargerByUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) WithContext(ctx context.Context) *GetEVChargerByUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) WithHTTPClient(client *http.Client) *GetEVChargerByUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) WithAuthorization(authorization *string) *GetEVChargerByUUIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithChargerUUID adds the chargerUUID to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) WithChargerUUID(chargerUUID string) *GetEVChargerByUUIDParams {
	o.SetChargerUUID(chargerUUID)
	return o
}

// SetChargerUUID adds the chargerUuid to the get e v charger by UUID params
func (o *GetEVChargerByUUIDParams) SetChargerUUID(chargerUUID string) {
	o.ChargerUUID = chargerUUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEVChargerByUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param charger_uuid
	if err := r.SetPathParam("charger_uuid", o.ChargerUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
