// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDataPointsParams creates a new GetDataPointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDataPointsParams() *GetDataPointsParams {
	return &GetDataPointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDataPointsParamsWithTimeout creates a new GetDataPointsParams object
// with the ability to set a timeout on a request.
func NewGetDataPointsParamsWithTimeout(timeout time.Duration) *GetDataPointsParams {
	return &GetDataPointsParams{
		timeout: timeout,
	}
}

// NewGetDataPointsParamsWithContext creates a new GetDataPointsParams object
// with the ability to set a context for a request.
func NewGetDataPointsParamsWithContext(ctx context.Context) *GetDataPointsParams {
	return &GetDataPointsParams{
		Context: ctx,
	}
}

// NewGetDataPointsParamsWithHTTPClient creates a new GetDataPointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDataPointsParamsWithHTTPClient(client *http.Client) *GetDataPointsParams {
	return &GetDataPointsParams{
		HTTPClient: client,
	}
}

/*
GetDataPointsParams contains all the parameters to send to the API endpoint

	for the get data points operation.

	Typically these are written to a http.Request.
*/
type GetDataPointsParams struct {

	// Authorization.
	Authorization *string

	/* ChargerUUID.

	   The UUID of the charger.
	*/
	ChargerUUID string

	/* EndTime.

	   The time of the latest data point. Must be a valid date. Must be a date after <code>start_time</code>.
	*/
	EndTime string

	/* Measurands.

	   One or more measurands to filter by.
	*/
	Measurands []string

	/* MeterIds.

	   The IDs of the measuring devices to fetch data for.
	*/
	MeterIds []int64

	/* Page.

	   Page number to return
	*/
	Page *int64

	/* PageSize.

	   Number of items to return in a page. Defaults to 15
	*/
	PageSize *int64

	/* StartTime.

	   The time of the earliest data point. Must be a valid date. Must be a date before <code>now</code>.
	*/
	StartTime string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get data points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataPointsParams) WithDefaults() *GetDataPointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get data points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDataPointsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get data points params
func (o *GetDataPointsParams) WithTimeout(timeout time.Duration) *GetDataPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get data points params
func (o *GetDataPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get data points params
func (o *GetDataPointsParams) WithContext(ctx context.Context) *GetDataPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get data points params
func (o *GetDataPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get data points params
func (o *GetDataPointsParams) WithHTTPClient(client *http.Client) *GetDataPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get data points params
func (o *GetDataPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get data points params
func (o *GetDataPointsParams) WithAuthorization(authorization *string) *GetDataPointsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get data points params
func (o *GetDataPointsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithChargerUUID adds the chargerUUID to the get data points params
func (o *GetDataPointsParams) WithChargerUUID(chargerUUID string) *GetDataPointsParams {
	o.SetChargerUUID(chargerUUID)
	return o
}

// SetChargerUUID adds the chargerUuid to the get data points params
func (o *GetDataPointsParams) SetChargerUUID(chargerUUID string) {
	o.ChargerUUID = chargerUUID
}

// WithEndTime adds the endTime to the get data points params
func (o *GetDataPointsParams) WithEndTime(endTime string) *GetDataPointsParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get data points params
func (o *GetDataPointsParams) SetEndTime(endTime string) {
	o.EndTime = endTime
}

// WithMeasurands adds the measurands to the get data points params
func (o *GetDataPointsParams) WithMeasurands(measurands []string) *GetDataPointsParams {
	o.SetMeasurands(measurands)
	return o
}

// SetMeasurands adds the measurands to the get data points params
func (o *GetDataPointsParams) SetMeasurands(measurands []string) {
	o.Measurands = measurands
}

// WithMeterIds adds the meterIds to the get data points params
func (o *GetDataPointsParams) WithMeterIds(meterIds []int64) *GetDataPointsParams {
	o.SetMeterIds(meterIds)
	return o
}

// SetMeterIds adds the meterIds to the get data points params
func (o *GetDataPointsParams) SetMeterIds(meterIds []int64) {
	o.MeterIds = meterIds
}

// WithPage adds the page to the get data points params
func (o *GetDataPointsParams) WithPage(page *int64) *GetDataPointsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get data points params
func (o *GetDataPointsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get data points params
func (o *GetDataPointsParams) WithPageSize(pageSize *int64) *GetDataPointsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get data points params
func (o *GetDataPointsParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithStartTime adds the startTime to the get data points params
func (o *GetDataPointsParams) WithStartTime(startTime string) *GetDataPointsParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get data points params
func (o *GetDataPointsParams) SetStartTime(startTime string) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetDataPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param charger_uuid
	if err := r.SetPathParam("charger_uuid", o.ChargerUUID); err != nil {
		return err
	}

	// query param end_time
	qrEndTime := o.EndTime
	qEndTime := qrEndTime
	if qEndTime != "" {

		if err := r.SetQueryParam("end_time", qEndTime); err != nil {
			return err
		}
	}

	if o.Measurands != nil {

		// binding items for measurands
		joinedMeasurands := o.bindParamMeasurands(reg)

		// query array param measurands
		if err := r.SetQueryParam("measurands", joinedMeasurands...); err != nil {
			return err
		}
	}

	if o.MeterIds != nil {

		// binding items for meter_ids
		joinedMeterIds := o.bindParamMeterIds(reg)

		// query array param meter_ids
		if err := r.SetQueryParam("meter_ids", joinedMeterIds...); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	// query param start_time
	qrStartTime := o.StartTime
	qStartTime := qrStartTime
	if qStartTime != "" {

		if err := r.SetQueryParam("start_time", qStartTime); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetDataPoints binds the parameter measurands
func (o *GetDataPointsParams) bindParamMeasurands(formats strfmt.Registry) []string {
	measurandsIR := o.Measurands

	var measurandsIC []string
	for _, measurandsIIR := range measurandsIR { // explode []string

		measurandsIIV := measurandsIIR // string as string
		measurandsIC = append(measurandsIC, measurandsIIV)
	}

	// items.CollectionFormat: "multi"
	measurandsIS := swag.JoinByFormat(measurandsIC, "multi")

	return measurandsIS
}

// bindParamGetDataPoints binds the parameter meter_ids
func (o *GetDataPointsParams) bindParamMeterIds(formats strfmt.Registry) []string {
	meterIdsIR := o.MeterIds

	var meterIdsIC []string
	for _, meterIdsIIR := range meterIdsIR { // explode []int64

		meterIdsIIV := swag.FormatInt64(meterIdsIIR) // int64 as string
		meterIdsIC = append(meterIdsIC, meterIdsIIV)
	}

	// items.CollectionFormat: "multi"
	meterIdsIS := swag.JoinByFormat(meterIdsIC, "multi")

	return meterIdsIS
}
