// Code generated by go-swagger; DO NOT EDIT.

package e_v_charger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SendCommandReader is a Reader for the SendCommand structure.
type SendCommandReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendCommandReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendCommandOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSendCommandOK creates a SendCommandOK with default headers values
func NewSendCommandOK() *SendCommandOK {
	return &SendCommandOK{}
}

/*
SendCommandOK describes a response with status code 200, with default header values.

SendCommandOK send command o k
*/
type SendCommandOK struct {
	Payload *SendCommandOKBody
}

// IsSuccess returns true when this send command o k response has a 2xx status code
func (o *SendCommandOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this send command o k response has a 3xx status code
func (o *SendCommandOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this send command o k response has a 4xx status code
func (o *SendCommandOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this send command o k response has a 5xx status code
func (o *SendCommandOK) IsServerError() bool {
	return false
}

// IsCode returns true when this send command o k response a status code equal to that given
func (o *SendCommandOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the send command o k response
func (o *SendCommandOK) Code() int {
	return 200
}

func (o *SendCommandOK) Error() string {
	return fmt.Sprintf("[POST /ev-charger/{charger_uuid}/commands/{command_id}][%d] sendCommandOK  %+v", 200, o.Payload)
}

func (o *SendCommandOK) String() string {
	return fmt.Sprintf("[POST /ev-charger/{charger_uuid}/commands/{command_id}][%d] sendCommandOK  %+v", 200, o.Payload)
}

func (o *SendCommandOK) GetPayload() *SendCommandOKBody {
	return o.Payload
}

func (o *SendCommandOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SendCommandOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
SendCommandOKBody send command o k body
// Example: {"data":{"code":0,"message":"Accepted","success":true}}
swagger:model SendCommandOKBody
*/
type SendCommandOKBody struct {

	// data
	Data *SendCommandOKBodyData `json:"data,omitempty"`
}

// Validate validates this send command o k body
func (o *SendCommandOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendCommandOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sendCommandOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sendCommandOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this send command o k body based on the context it is used
func (o *SendCommandOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SendCommandOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sendCommandOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("sendCommandOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SendCommandOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendCommandOKBody) UnmarshalBinary(b []byte) error {
	var res SendCommandOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SendCommandOKBodyData send command o k body data
swagger:model SendCommandOKBodyData
*/
type SendCommandOKBodyData struct {

	// code
	// Example: 0
	Code int64 `json:"code,omitempty"`

	// message
	// Example: Accepted
	Message string `json:"message,omitempty"`

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this send command o k body data
func (o *SendCommandOKBodyData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this send command o k body data based on context it is used
func (o *SendCommandOKBodyData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SendCommandOKBodyData) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SendCommandOKBodyData) UnmarshalBinary(b []byte) error {
	var res SendCommandOKBodyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
