// Code generated by go-swagger; DO NOT EDIT.

package inverter_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPresetValuesReader is a Reader for the GetPresetValues structure.
type GetPresetValuesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPresetValuesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPresetValuesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /inverter/{inverter_serial_number}/presets/{id}] getPresetValues", response, response.Code())
	}
}

// NewGetPresetValuesOK creates a GetPresetValuesOK with default headers values
func NewGetPresetValuesOK() *GetPresetValuesOK {
	return &GetPresetValuesOK{}
}

/*
GetPresetValuesOK describes a response with status code 200, with default header values.

GetPresetValuesOK get preset values o k
*/
type GetPresetValuesOK struct {
	Payload string
}

// IsSuccess returns true when this get preset values o k response has a 2xx status code
func (o *GetPresetValuesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get preset values o k response has a 3xx status code
func (o *GetPresetValuesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get preset values o k response has a 4xx status code
func (o *GetPresetValuesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get preset values o k response has a 5xx status code
func (o *GetPresetValuesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get preset values o k response a status code equal to that given
func (o *GetPresetValuesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get preset values o k response
func (o *GetPresetValuesOK) Code() int {
	return 200
}

func (o *GetPresetValuesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inverter/{inverter_serial_number}/presets/{id}][%d] getPresetValuesOK %s", 200, payload)
}

func (o *GetPresetValuesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inverter/{inverter_serial_number}/presets/{id}][%d] getPresetValuesOK %s", 200, payload)
}

func (o *GetPresetValuesOK) GetPayload() string {
	return o.Payload
}

func (o *GetPresetValuesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
