// Code generated by go-swagger; DO NOT EDIT.

package inverter_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPresetValuesParams creates a new GetPresetValuesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPresetValuesParams() *GetPresetValuesParams {
	return &GetPresetValuesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPresetValuesParamsWithTimeout creates a new GetPresetValuesParams object
// with the ability to set a timeout on a request.
func NewGetPresetValuesParamsWithTimeout(timeout time.Duration) *GetPresetValuesParams {
	return &GetPresetValuesParams{
		timeout: timeout,
	}
}

// NewGetPresetValuesParamsWithContext creates a new GetPresetValuesParams object
// with the ability to set a context for a request.
func NewGetPresetValuesParamsWithContext(ctx context.Context) *GetPresetValuesParams {
	return &GetPresetValuesParams{
		Context: ctx,
	}
}

// NewGetPresetValuesParamsWithHTTPClient creates a new GetPresetValuesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPresetValuesParamsWithHTTPClient(client *http.Client) *GetPresetValuesParams {
	return &GetPresetValuesParams{
		HTTPClient: client,
	}
}

/*
GetPresetValuesParams contains all the parameters to send to the API endpoint

	for the get preset values operation.

	Typically these are written to a http.Request.
*/
type GetPresetValuesParams struct {

	// Authorization.
	Authorization *string

	/* ID.

	   The preset ID (`identifier`), as returned by the API or defined in the documentation
	*/
	ID string

	/* InverterSerialNumber.

	   The serial number of the inverter.
	*/
	InverterSerialNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get preset values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresetValuesParams) WithDefaults() *GetPresetValuesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get preset values params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresetValuesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get preset values params
func (o *GetPresetValuesParams) WithTimeout(timeout time.Duration) *GetPresetValuesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get preset values params
func (o *GetPresetValuesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get preset values params
func (o *GetPresetValuesParams) WithContext(ctx context.Context) *GetPresetValuesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get preset values params
func (o *GetPresetValuesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get preset values params
func (o *GetPresetValuesParams) WithHTTPClient(client *http.Client) *GetPresetValuesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get preset values params
func (o *GetPresetValuesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get preset values params
func (o *GetPresetValuesParams) WithAuthorization(authorization *string) *GetPresetValuesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get preset values params
func (o *GetPresetValuesParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithID adds the id to the get preset values params
func (o *GetPresetValuesParams) WithID(id string) *GetPresetValuesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get preset values params
func (o *GetPresetValuesParams) SetID(id string) {
	o.ID = id
}

// WithInverterSerialNumber adds the inverterSerialNumber to the get preset values params
func (o *GetPresetValuesParams) WithInverterSerialNumber(inverterSerialNumber string) *GetPresetValuesParams {
	o.SetInverterSerialNumber(inverterSerialNumber)
	return o
}

// SetInverterSerialNumber adds the inverterSerialNumber to the get preset values params
func (o *GetPresetValuesParams) SetInverterSerialNumber(inverterSerialNumber string) {
	o.InverterSerialNumber = inverterSerialNumber
}

// WriteToRequest writes these params to a swagger request
func (o *GetPresetValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param inverter_serial_number
	if err := r.SetPathParam("inverter_serial_number", o.InverterSerialNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
