// Code generated by go-swagger; DO NOT EDIT.

package inverter_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewModifySettingMultipleParams creates a new ModifySettingMultipleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifySettingMultipleParams() *ModifySettingMultipleParams {
	return &ModifySettingMultipleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifySettingMultipleParamsWithTimeout creates a new ModifySettingMultipleParams object
// with the ability to set a timeout on a request.
func NewModifySettingMultipleParamsWithTimeout(timeout time.Duration) *ModifySettingMultipleParams {
	return &ModifySettingMultipleParams{
		timeout: timeout,
	}
}

// NewModifySettingMultipleParamsWithContext creates a new ModifySettingMultipleParams object
// with the ability to set a context for a request.
func NewModifySettingMultipleParamsWithContext(ctx context.Context) *ModifySettingMultipleParams {
	return &ModifySettingMultipleParams{
		Context: ctx,
	}
}

// NewModifySettingMultipleParamsWithHTTPClient creates a new ModifySettingMultipleParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifySettingMultipleParamsWithHTTPClient(client *http.Client) *ModifySettingMultipleParams {
	return &ModifySettingMultipleParams{
		HTTPClient: client,
	}
}

/*
ModifySettingMultipleParams contains all the parameters to send to the API endpoint

	for the modify setting multiple operation.

	Typically these are written to a http.Request.
*/
type ModifySettingMultipleParams struct {

	// Authorization.
	Authorization *string

	// Body.
	Body ModifySettingMultipleBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify setting multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifySettingMultipleParams) WithDefaults() *ModifySettingMultipleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify setting multiple params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifySettingMultipleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify setting multiple params
func (o *ModifySettingMultipleParams) WithTimeout(timeout time.Duration) *ModifySettingMultipleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify setting multiple params
func (o *ModifySettingMultipleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify setting multiple params
func (o *ModifySettingMultipleParams) WithContext(ctx context.Context) *ModifySettingMultipleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify setting multiple params
func (o *ModifySettingMultipleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify setting multiple params
func (o *ModifySettingMultipleParams) WithHTTPClient(client *http.Client) *ModifySettingMultipleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify setting multiple params
func (o *ModifySettingMultipleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the modify setting multiple params
func (o *ModifySettingMultipleParams) WithAuthorization(authorization *string) *ModifySettingMultipleParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the modify setting multiple params
func (o *ModifySettingMultipleParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the modify setting multiple params
func (o *ModifySettingMultipleParams) WithBody(body ModifySettingMultipleBody) *ModifySettingMultipleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify setting multiple params
func (o *ModifySettingMultipleParams) SetBody(body ModifySettingMultipleBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifySettingMultipleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
