// Code generated by go-swagger; DO NOT EDIT.

package inverter_control

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewModifySettingParams creates a new ModifySettingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifySettingParams() *ModifySettingParams {
	return &ModifySettingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifySettingParamsWithTimeout creates a new ModifySettingParams object
// with the ability to set a timeout on a request.
func NewModifySettingParamsWithTimeout(timeout time.Duration) *ModifySettingParams {
	return &ModifySettingParams{
		timeout: timeout,
	}
}

// NewModifySettingParamsWithContext creates a new ModifySettingParams object
// with the ability to set a context for a request.
func NewModifySettingParamsWithContext(ctx context.Context) *ModifySettingParams {
	return &ModifySettingParams{
		Context: ctx,
	}
}

// NewModifySettingParamsWithHTTPClient creates a new ModifySettingParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifySettingParamsWithHTTPClient(client *http.Client) *ModifySettingParams {
	return &ModifySettingParams{
		HTTPClient: client,
	}
}

/*
ModifySettingParams contains all the parameters to send to the API endpoint

	for the modify setting operation.

	Typically these are written to a http.Request.
*/
type ModifySettingParams struct {

	// Authorization.
	Authorization *string

	// Body.
	Body ModifySettingBody

	/* InverterSerialNumber.

	   The serial number of the inverter.
	*/
	InverterSerialNumber string

	/* SettingID.

	   The ID of the setting.
	*/
	SettingID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify setting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifySettingParams) WithDefaults() *ModifySettingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify setting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifySettingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify setting params
func (o *ModifySettingParams) WithTimeout(timeout time.Duration) *ModifySettingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify setting params
func (o *ModifySettingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify setting params
func (o *ModifySettingParams) WithContext(ctx context.Context) *ModifySettingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify setting params
func (o *ModifySettingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify setting params
func (o *ModifySettingParams) WithHTTPClient(client *http.Client) *ModifySettingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify setting params
func (o *ModifySettingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the modify setting params
func (o *ModifySettingParams) WithAuthorization(authorization *string) *ModifySettingParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the modify setting params
func (o *ModifySettingParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the modify setting params
func (o *ModifySettingParams) WithBody(body ModifySettingBody) *ModifySettingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify setting params
func (o *ModifySettingParams) SetBody(body ModifySettingBody) {
	o.Body = body
}

// WithInverterSerialNumber adds the inverterSerialNumber to the modify setting params
func (o *ModifySettingParams) WithInverterSerialNumber(inverterSerialNumber string) *ModifySettingParams {
	o.SetInverterSerialNumber(inverterSerialNumber)
	return o
}

// SetInverterSerialNumber adds the inverterSerialNumber to the modify setting params
func (o *ModifySettingParams) SetInverterSerialNumber(inverterSerialNumber string) {
	o.InverterSerialNumber = inverterSerialNumber
}

// WithSettingID adds the settingID to the modify setting params
func (o *ModifySettingParams) WithSettingID(settingID int64) *ModifySettingParams {
	o.SetSettingID(settingID)
	return o
}

// SetSettingID adds the settingId to the modify setting params
func (o *ModifySettingParams) SetSettingID(settingID int64) {
	o.SettingID = settingID
}

// WriteToRequest writes these params to a swagger request
func (o *ModifySettingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param inverter_serial_number
	if err := r.SetPathParam("inverter_serial_number", o.InverterSerialNumber); err != nil {
		return err
	}

	// path param setting_id
	if err := r.SetPathParam("setting_id", swag.FormatInt64(o.SettingID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
