// Code generated by go-swagger; DO NOT EDIT.

package smart_device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateSmartDeviceDataPointParams creates a new CreateSmartDeviceDataPointParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateSmartDeviceDataPointParams() *CreateSmartDeviceDataPointParams {
	return &CreateSmartDeviceDataPointParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSmartDeviceDataPointParamsWithTimeout creates a new CreateSmartDeviceDataPointParams object
// with the ability to set a timeout on a request.
func NewCreateSmartDeviceDataPointParamsWithTimeout(timeout time.Duration) *CreateSmartDeviceDataPointParams {
	return &CreateSmartDeviceDataPointParams{
		timeout: timeout,
	}
}

// NewCreateSmartDeviceDataPointParamsWithContext creates a new CreateSmartDeviceDataPointParams object
// with the ability to set a context for a request.
func NewCreateSmartDeviceDataPointParamsWithContext(ctx context.Context) *CreateSmartDeviceDataPointParams {
	return &CreateSmartDeviceDataPointParams{
		Context: ctx,
	}
}

// NewCreateSmartDeviceDataPointParamsWithHTTPClient creates a new CreateSmartDeviceDataPointParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateSmartDeviceDataPointParamsWithHTTPClient(client *http.Client) *CreateSmartDeviceDataPointParams {
	return &CreateSmartDeviceDataPointParams{
		HTTPClient: client,
	}
}

/*
CreateSmartDeviceDataPointParams contains all the parameters to send to the API endpoint

	for the create smart device data point operation.

	Typically these are written to a http.Request.
*/
type CreateSmartDeviceDataPointParams struct {

	// Authorization.
	Authorization *string

	// Body.
	Body CreateSmartDeviceDataPointBody

	/* SmartDeviceUUID.

	   The UUID of the smartDevice.
	*/
	SmartDeviceUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create smart device data point params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSmartDeviceDataPointParams) WithDefaults() *CreateSmartDeviceDataPointParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create smart device data point params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateSmartDeviceDataPointParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithTimeout(timeout time.Duration) *CreateSmartDeviceDataPointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithContext(ctx context.Context) *CreateSmartDeviceDataPointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithHTTPClient(client *http.Client) *CreateSmartDeviceDataPointParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithAuthorization(authorization *string) *CreateSmartDeviceDataPointParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithBody adds the body to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithBody(body CreateSmartDeviceDataPointBody) *CreateSmartDeviceDataPointParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetBody(body CreateSmartDeviceDataPointBody) {
	o.Body = body
}

// WithSmartDeviceUUID adds the smartDeviceUUID to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) WithSmartDeviceUUID(smartDeviceUUID string) *CreateSmartDeviceDataPointParams {
	o.SetSmartDeviceUUID(smartDeviceUUID)
	return o
}

// SetSmartDeviceUUID adds the smartDeviceUuid to the create smart device data point params
func (o *CreateSmartDeviceDataPointParams) SetSmartDeviceUUID(smartDeviceUUID string) {
	o.SmartDeviceUUID = smartDeviceUUID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSmartDeviceDataPointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param smartDevice_uuid
	if err := r.SetPathParam("smartDevice_uuid", o.SmartDeviceUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
