// Code generated by go-swagger; DO NOT EDIT.

package energy_flow_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new energy flow data API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for energy flow data API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetEnergyFlowData(params *GetEnergyFlowDataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEnergyFlowDataOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetEnergyFlowData gets energy flow data

Fetches the energy flow data for a given inverter between 2 times
*/
func (a *Client) GetEnergyFlowData(params *GetEnergyFlowDataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetEnergyFlowDataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEnergyFlowDataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getEnergyFlowData",
		Method:             "POST",
		PathPattern:        "/inverter/{inverter_serial_number}/energy-flows",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetEnergyFlowDataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetEnergyFlowDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getEnergyFlowData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
