// Code generated by go-swagger; DO NOT EDIT.

package site

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetYourSitesParams creates a new GetYourSitesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetYourSitesParams() *GetYourSitesParams {
	return &GetYourSitesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetYourSitesParamsWithTimeout creates a new GetYourSitesParams object
// with the ability to set a timeout on a request.
func NewGetYourSitesParamsWithTimeout(timeout time.Duration) *GetYourSitesParams {
	return &GetYourSitesParams{
		timeout: timeout,
	}
}

// NewGetYourSitesParamsWithContext creates a new GetYourSitesParams object
// with the ability to set a context for a request.
func NewGetYourSitesParamsWithContext(ctx context.Context) *GetYourSitesParams {
	return &GetYourSitesParams{
		Context: ctx,
	}
}

// NewGetYourSitesParamsWithHTTPClient creates a new GetYourSitesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetYourSitesParamsWithHTTPClient(client *http.Client) *GetYourSitesParams {
	return &GetYourSitesParams{
		HTTPClient: client,
	}
}

/*
GetYourSitesParams contains all the parameters to send to the API endpoint

	for the get your sites operation.

	Typically these are written to a http.Request.
*/
type GetYourSitesParams struct {

	// Authorization.
	Authorization *string

	/* Page.

	   Page number to return
	*/
	Page *int64

	/* PageSize.

	   Number of items to return in a page. Defaults to 15
	*/
	PageSize *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get your sites params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYourSitesParams) WithDefaults() *GetYourSitesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get your sites params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYourSitesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get your sites params
func (o *GetYourSitesParams) WithTimeout(timeout time.Duration) *GetYourSitesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get your sites params
func (o *GetYourSitesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get your sites params
func (o *GetYourSitesParams) WithContext(ctx context.Context) *GetYourSitesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get your sites params
func (o *GetYourSitesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get your sites params
func (o *GetYourSitesParams) WithHTTPClient(client *http.Client) *GetYourSitesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get your sites params
func (o *GetYourSitesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get your sites params
func (o *GetYourSitesParams) WithAuthorization(authorization *string) *GetYourSitesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get your sites params
func (o *GetYourSitesParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithPage adds the page to the get your sites params
func (o *GetYourSitesParams) WithPage(page *int64) *GetYourSitesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get your sites params
func (o *GetYourSitesParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get your sites params
func (o *GetYourSitesParams) WithPageSize(pageSize *int64) *GetYourSitesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get your sites params
func (o *GetYourSitesParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *GetYourSitesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
