// Code generated by go-swagger; DO NOT EDIT.

package site

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateSiteStatusReader is a Reader for the UpdateSiteStatus structure.
type UpdateSiteStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSiteStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateSiteStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateSiteStatusOK creates a UpdateSiteStatusOK with default headers values
func NewUpdateSiteStatusOK() *UpdateSiteStatusOK {
	return &UpdateSiteStatusOK{}
}

/*
UpdateSiteStatusOK describes a response with status code 200, with default header values.

UpdateSiteStatusOK update site status o k
*/
type UpdateSiteStatusOK struct {
	Payload *UpdateSiteStatusOKBody
}

// IsSuccess returns true when this update site status o k response has a 2xx status code
func (o *UpdateSiteStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update site status o k response has a 3xx status code
func (o *UpdateSiteStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update site status o k response has a 4xx status code
func (o *UpdateSiteStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update site status o k response has a 5xx status code
func (o *UpdateSiteStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update site status o k response a status code equal to that given
func (o *UpdateSiteStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update site status o k response
func (o *UpdateSiteStatusOK) Code() int {
	return 200
}

func (o *UpdateSiteStatusOK) Error() string {
	return fmt.Sprintf("[POST /site/{site_plant_id}/status][%d] updateSiteStatusOK  %+v", 200, o.Payload)
}

func (o *UpdateSiteStatusOK) String() string {
	return fmt.Sprintf("[POST /site/{site_plant_id}/status][%d] updateSiteStatusOK  %+v", 200, o.Payload)
}

func (o *UpdateSiteStatusOK) GetPayload() *UpdateSiteStatusOKBody {
	return o.Payload
}

func (o *UpdateSiteStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateSiteStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateSiteStatusBody update site status body
swagger:model UpdateSiteStatusBody
*/
type UpdateSiteStatusBody struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this update site status body
func (o *UpdateSiteStatusBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update site status body based on context it is used
func (o *UpdateSiteStatusBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateSiteStatusBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateSiteStatusBody) UnmarshalBinary(b []byte) error {
	var res UpdateSiteStatusBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
UpdateSiteStatusOKBody update site status o k body
// Example: {"success":true}
swagger:model UpdateSiteStatusOKBody
*/
type UpdateSiteStatusOKBody struct {

	// success
	// Example: true
	Success bool `json:"success,omitempty"`
}

// Validate validates this update site status o k body
func (o *UpdateSiteStatusOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update site status o k body based on context it is used
func (o *UpdateSiteStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateSiteStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateSiteStatusOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateSiteStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
